spring:
  mail:
    host: smtp.gmail.com
    username: birthdaypostbox@gmail.com
    port: '25'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: xxxx
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/birthday_postbox?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  output:
    ansi:
      enabled: always
  profiles:
    include:
      - credentials
server:
  address: localhost
  port: '8080'
logging:
  level:
    org:
      hibernate: info

